name: Demo 4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  Question-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo ${{ secrets.API_KEY}}
      - run: echo $API_KEY 
