Name: Demo 4

on:
  push:
    main
  pull_request:
    main

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  Question-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo "::add-mask::${{ secrets.API_KEY}}"
      - run : echo $API_KEY 
